echo setup...
rm -rf /plex_data/tmp
mkdir /plex_data/tmp
echo downloading...
curl -s "https://plex.tv/downloads/details/1?build=linux-ubuntu-x86_64&channel=16&distro=ubuntu" | grep -Po '(?<=url=\")(\S+)(?=\")' | xargs wget -P /plex_data/tmp/
echo installing...
sudo dpkg -i /plex_data/tmp/plexmediaserver*
echo cleanin up...
rm -rf /plex_data/tmp
echo update completed
