echo setup...
rm -rf /tmp/plexserver
mkdir /tmp/plexserver
echo downloading...
curl -s "https://plex.tv/downloads/details/1?build=linux-ubuntu-x86_64&channel=16&distro=ubuntu" | grep -Po '(?<=url=\")(\S+)(?=\")' | xargs wget -P /tmp/plexserver/
echo installing...
sudo dpkg -i /tmp/plexserver/plexmediaserver*
echo cleanin up...
rm -rf /tmp/plexserver
echo update completed
